# Generated by Django 4.2 on 2023-08-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('naran', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fasilidade',
            fields=[
                ('data_kria', models.DateTimeField(auto_now_add=True)),
                ('data_modifika', models.DateTimeField(auto_now=True)),
                ('naran', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='fasilidade')),
                ('deskrisaun', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaProdutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEscola',
            fields=[
                ('naran', models.CharField(max_length=150)),
                ('enderesu', models.CharField(max_length=100)),
                ('data_estabelece', models.DateField(verbose_name='Data estabelece')),
                ('naran_director', models.CharField(max_length=255)),
                ('img_director', models.ImageField(upload_to='perfil')),
                ('liamenon_director', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('youtube', models.URLField()),
                ('facebook', models.URLField()),
                ('nu_kontaktu', models.CharField(max_length=13)),
                ('logo', models.ImageField(upload_to='perfil')),
                ('historia', models.TextField()),
                ('vizaun', models.TextField()),
                ('misaun', models.TextField()),
                ('objetivu', models.TextField()),
                ('total_estudante', models.IntegerField(default=0)),
                ('total_manorin', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fasilidade', models.ManyToManyField(blank=True, to='eti.fasilidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfilescolas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notisia',
            fields=[
                ('data_publikasaun', models.DateTimeField(auto_now_add=True)),
                ('data_modifika', models.DateTimeField(auto_now=True)),
                ('titulu', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='notisia')),
                ('content', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autors', to='eti.autor')),
                ('categoria', models.ManyToManyField(blank=True, to='eti.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('data_publikasaun', models.DateTimeField(auto_now_add=True)),
                ('data_modifika', models.DateTimeField(auto_now=True)),
                ('titulu', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='galeri')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeris', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('data_kria', models.DateTimeField(auto_now_add=True)),
                ('data_modifika', models.DateTimeField(auto_now=True)),
                ('naran', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='departamento')),
                ('deskrisaun', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('atividade_prinsipal', models.ManyToManyField(blank=True, to='eti.atividadeprincipal')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='eti.perfilescola')),
                ('programa_cientifico', models.ManyToManyField(blank=True, to='eti.programacientifico')),
                ('programa_produtivo', models.ManyToManyField(blank=True, to='eti.programaprodutivo')),
                ('programa_socio', models.ManyToManyField(blank=True, to='eti.programasocio')),
            ],
        ),
    ]
